language: node_js
node_js:
  - "8.12"
  - "8"
  - "10.3"
  - "10"
  - "12.0"
  - "12"
  - "lts/*"
  - "node"
install:
  - npm ci
script:
  - npm test
  # Make sure it still builds successfully - the build isn't actually used yet:
  - npm run build
# FIXME: https://github.com/solid/solid-panes/issues/220
# before_deploy:
#   - node ./travis/bumpversion.js
# deploy:
#   provider: npm
#   # Do not throw away the updated package.json we generated in `before_deploy`:
#   skip_cleanup: true
#   email: '$NPM_EMAIL'
#   api_key: '$NPM_TOKEN'
#   # Note: do not deploy on pull request, because $TRAVIS_BRANCH will be the target branch.
#   tag: '$TRAVIS_BRANCH'
#   on:
#     all_branches: true
