/* The text refactor was generated by AI Model: GPT-5.4-Copilot. */
export * from './texts/buttonTexts'
export * from './texts/dialogTexts'
export * from './texts/messageTexts'
export * from './texts/profileTexts'
export * from './texts/qrCodeTexts'
