import { RowStatus } from './types'

export type EditableRow = {
  entryNode: string
  status: RowStatus
}

export type TypedEditableRow = EditableRow & {
  type: string
}

type StringKeyOf<T> = {
  [K in keyof T]-?: T[K] extends string ? K : never
}[keyof T]

export function deleteRow<T extends EditableRow> (rows: T[], index: number) {
  const row = rows[index]
  if (!row) return

  if (row.entryNode) {
    row.status = 'deleted'
    return
  }

  rows.splice(index, 1)
}

export function applyRowSelectChange<T extends EditableRow, K extends StringKeyOf<T>> (
  row: T,
  field: K,
  nextValue: Extract<T[K], string>
) {
  row[field] = nextValue.trim() as T[K]

  if (row.entryNode) {
    row.status = row.status === 'existing' || row.status === 'deleted' ? 'modified' : row.status
    return
  }

  row.status = 'new'
}

export function summarizeRowOps<T extends EditableRow> (rows: T[], rowHasContent: (row: T) => boolean) {
  const create = rows.filter((row) => row.status === 'new' && rowHasContent(row))
  const update = rows.filter((row) => row.status === 'modified' && rowHasContent(row))
  const remove = rows.filter((row) => row.status === 'deleted')
  return { create, update, remove }
}

/* The following function was generated by AI Model: GPT-5.3-Codex  */
/* it was originally only for addresses but I made it more generic so it can be used for any type of rows */
/* Prompt: can you have applyAddressFieldChange update the row status based on whether any fields have content */
export function applyRowFieldChange<T extends EditableRow, K extends keyof T> (
  row: T,
  field: K,
  nextValue: T[K],
  hasContent: (row: T) => boolean
) {
  row[field] = nextValue

  if (!hasContent(row)) {
    row.status = row.entryNode ? 'deleted' : 'new'
    return
  }

  if (row.entryNode) {
    row.status = row.status === 'existing' || row.status === 'deleted' ? 'modified' : row.status
    return
  }

  row.status = 'new'
}
