/*      Data content Pane
 **
 **  This pane shows the content of a particular RDF resource
 ** or at least the RDF semantics we attribute to that resource.
 */

// To do:  - Only take data from one graph
//         - Only do forwards not backward?
//         - Expand automatically all the way down
//         - original source view?  Use ffox view source

import * as UI from 'solid-ui'
import * as $rdf from 'rdflib'
import DOMPurify from 'dompurify'
import type { DataBrowserContext, RenderEnvironment } from 'pane-registry'
import type {
  BlankNode,
  Formula,
  NamedNode,
  Statement
} from 'rdflib'
import './dataContentPane.css'

const ns = UI.ns

type SubjectTerm = NamedNode | BlankNode
type ObjectTerm = Statement['object'] | Formula

type RootSubjectsResult = {
  roots: SubjectTerm[]
  subjects: Record<string, Statement[]>
  loopBreakers?: Record<string, unknown>
}

type DataContentPaneLike = {
  statementsAsTables: (
    sts: Statement[],
    context: DataBrowserContext,
    initialRoots?: SubjectTerm[]
  ) => HTMLElement
}

export const dataContentPane = {
  icon: UI.icons.originalIconBase + 'rdf_flyer.24.gif',

  name: 'dataContents',

  audience: [ns.solid('Developer')],

  label: function (subject: NamedNode, context: DataBrowserContext) {
    if (
      'http://www.w3.org/2007/ont/link#ProtocolEvent' in
      context.session.store.findTypeURIs(subject)
    ) {
      return null
    }
    const n = context.session.store.statementsMatching(
      undefined,
      undefined,
      undefined,
      subject
    ).length
    if (n === 0) return null
    return 'Data (' + n + ')'
  },
  /*
  shouldGetFocus: function(subject) {
      return store.whether(subject, UI.ns.rdf('type'), UI.ns.link('RDFDocument'))
  },
*/
  /* This code was generated by Generative AI (GPT-5.3-Codex in GitHub Copilot) based on the following prompt:
  Only the class assignments of data-content-pane__nested-table--light and
  data-content-pane__nested-table--dark
  are the only things added by AI.

  This is the comment I got from copilot, but suggested fix remove the dark
  class as well The nested table shading logic checks
  UI.utils.ancestor(newTable, 'TABLE') immediately after
  creating newTable, but at that moment newTable typically has no
  parent in the DOM yet. This makes parentTable null and will
  always apply data-content-pane__nested-table--light, preventing the
  intended alternating light/dark nested backgrounds.
  Consider assigning the class after appending newTable into
  its parent table, or pass the parent table (or current nesting
  depth) into objectTree() so the decision can be made reliably.
  can you help me fix this without removing the dark altering */
  statementsAsTables: function statementsAsTables (
    sts: Statement[],
    context: DataBrowserContext,
    initialRoots?: SubjectTerm[]
  ): HTMLElement {
    const myDocument = context.dom
    const rep = myDocument.createElement('section')
    rep.classList.add('data-content', 'data-content-pane__root')
    const sz = $rdf.Serializer(context.session.store)
    const res = sz.rootSubjects(sts) as RootSubjectsResult
    let roots = res.roots
    const subjects = res.subjects
    const loopBreakers = res.loopBreakers ?? {}
    for (const x in loopBreakers) {
      console.log('\tdataContentPane: loopbreaker:' + x)
    }
    const doneBnodes: Record<string, true | HTMLDListElement> = {}
    const referencedBnodes: Record<string, true> = {}

    function propertyTree (
      subject: SubjectTerm,
      nestingLevel = 0
    ): HTMLDListElement {
      const rep = myDocument.createElement('dl')
      rep.classList.add('property-list', 'data-content-pane__property-list')
      let lastPred: string | null = null
      const subjectStatements = subjects[sz.toStr(subject)]
      if (!subjectStatements) {
        rep.appendChild(myDocument.createTextNode('...'))
        return rep
      }
      subjectStatements.sort()
      for (const st of subjectStatements) {
        if (st.predicate.uri !== lastPred) {
          const dt = myDocument.createElement('dt')
          dt.classList.add('pred', 'data-content-pane__predicate')
          const anchor = myDocument.createElement('a')
          anchor.setAttribute('href', st.predicate.uri)
          anchor.addEventListener(
            'click',
            UI.widgets.openHrefInOutlineMode,
            true
          )
          anchor.appendChild(
            myDocument.createTextNode(
              UI.utils.predicateLabelForXML(st.predicate)
            )
          )
          dt.appendChild(anchor)
          rep.appendChild(dt)
          lastPred = st.predicate.uri
        }
        const dd = myDocument.createElement('dd')
        dd.classList.add('obj', 'data-content-pane__value')
        dd.appendChild(objectTree(st.object, nestingLevel + 1))
        rep.appendChild(dd)
      }
      return rep
    }

    function objectTree (obj: ObjectTerm, nestingLevel = 0): Node {
      let res: HTMLElement | Text
      let anchor: HTMLAnchorElement
      switch (obj.termType) {
        case 'NamedNode':
          anchor = myDocument.createElement('a')
          anchor.setAttribute('href', obj.uri)
          anchor.addEventListener(
            'click',
            UI.widgets.openHrefInOutlineMode,
            true
          )
          anchor.appendChild(myDocument.createTextNode(UI.utils.label(obj)))
          return anchor

        case 'Literal':
          if (!obj.datatype || !obj.datatype.uri) {
            res = myDocument.createElement('div')
            res.classList.add('data-content-pane__literal')
            res.textContent = obj.value
            return res
          } else if (
            obj.datatype.uri ===
            'http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral'
          ) {
            res = myDocument.createElement('div')
            res.classList.add('embeddedXHTML')
            res.innerHTML = DOMPurify.sanitize(obj.value)
            return res
          }
          return myDocument.createTextNode(obj.value)

        case 'BlankNode': {
          if (obj.toNT() in doneBnodes) {
            referencedBnodes[obj.toNT()] = true
            const referenceAnchor = myDocument.createElement('a')
            referenceAnchor.setAttribute('href', '#' + obj.toNT().slice(2))
            referenceAnchor.setAttribute('class', 'bnodeRef')
            referenceAnchor.textContent = '*' + obj.toNT().slice(3)
            return referenceAnchor
          }
          doneBnodes[obj.toNT()] = true
          const newList = propertyTree(obj, nestingLevel)
          doneBnodes[obj.toNT()] = newList
          if (nestingLevel % 2 === 1) {
            newList.classList.add('data-content-pane__nested-table--light')
          } else {
            newList.classList.add('data-content-pane__nested-table--dark')
          }
          return newList
        }

        case 'Collection': {
          const list = myDocument.createElement('ol')
          list.setAttribute('class', 'collectionAsTables')
          for (let i = 0; i < obj.elements.length; i++) {
            const li = myDocument.createElement('li')
            li.appendChild(objectTree(obj.elements[i] as ObjectTerm, nestingLevel + 1))
            list.appendChild(li)
          }
          return list
        }

        case 'Graph':
          res = (context.session.paneRegistry
            .byName('dataContents') as DataContentPaneLike)
            .statementsAsTables(obj.statements, context)
          res.setAttribute('class', 'data-content-pane__nested-formula')
          return res

        case 'Variable':
          return myDocument.createTextNode('?' + obj.uri)
      }
      throw new Error('Unhandled node type: ' + obj.termType)
    }

    if (initialRoots) {
      roots = initialRoots.concat(
        roots.filter(function (x: SubjectTerm) {
          for (let i = 0; i < initialRoots.length; i++) {
            if (x.sameTerm(initialRoots[i])) return false
          }
          return true
        })
      )
    }
    for (let i = 0; i < roots.length; i++) {
      const block = myDocument.createElement('article')
      block.classList.add(
        i % 2 === 0 ? 'data-content-pane__row--even' : 'data-content-pane__row--odd',
        'data-content-pane__subject-block'
      )
      const header = myDocument.createElement('header')
      header.classList.add('data-content-pane__subject-cell')
      const root = roots[i]
      if (root.termType === 'BlankNode') {
        header.appendChild(myDocument.createTextNode(UI.utils.label(root)))
      } else {
        header.appendChild(objectTree(root, 0))
      }
      block.appendChild(header)
      block.appendChild(propertyTree(root, 0))
      rep.appendChild(block)
    }
    for (const bNT in referencedBnodes) {
      const list = doneBnodes[bNT]
      if (list === true) continue
      const anchor = myDocument.createElement('a')
      anchor.setAttribute('id', bNT.slice(2))
      anchor.setAttribute('class', 'bnodeDef')
      anchor.textContent = bNT.slice(3) + ')'
      list.insertBefore(anchor, list.firstChild)
    }
    return rep
  },

  render: function (
    subject: NamedNode,
    context: DataBrowserContext
  ): HTMLDivElement {
    const myDocument = context.dom

    function applyEnvironmentAttributes (element: HTMLDivElement): void {
      const environment = (context.environment ?? {}) as Partial<RenderEnvironment>
      element.dataset.layout = environment.layout ?? 'desktop'
      element.dataset.theme = environment.theme ?? 'light'
      element.dataset.inputMode = environment.inputMode ?? 'pointer'
    }

    function mainRendering () {
      const kb = context.session.store
      const sts = kb.statementsMatching(undefined, undefined, undefined, subject)
      const initialRoots: SubjectTerm[] = []
      if (kb.holds(subject, undefined, undefined, subject)) {
        initialRoots.push(subject)
      }
      const ps = kb.any(subject, UI.ns.foaf('primaryTopic'), undefined, subject)
      if (ps && (ps.termType === 'NamedNode' || ps.termType === 'BlankNode')) {
        initialRoots.push(ps as SubjectTerm)
      }

      div.appendChild(
        context.session.paneRegistry
          .byName('dataContents')
          .statementsAsTables(sts, context, initialRoots)
      )
    }

    const div = myDocument.createElement('div')
    div.classList.add('dataContentPane', 'data-content-pane')
    applyEnvironmentAttributes(div)

    mainRendering()
    return div
  }
}
